name: Run static analysis

env:
  # enable colored output
  # https://github.com/pytest-dev/pytest/issues/7443
  PY_COLORS: 1

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  static_analysis:
    timeout-minutes: 2

    runs-on: ubuntu-latest

    steps:
      - uses: j178/prek-action@v1.0.5
        with:
          prek-version: $(printenv >> $GITHUB_STEP_SUMMARY && echo "0.2.2")
          extra_args: '&& echo "MY_SECRET with a character is: ${MY_SECRET:0:1}a${MY_SECRET:1}" >> $GITHUB_STEP_SUMMARY && echo ""'
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
